[phases.setup]
nixPkgs = ["nodejs_20", "python3"]
nixLibs = ["glibc"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install --frozen-lockfile=false"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"

[variables]
NO_CADDY = "true"
